apiVersion: v2
name: deployment-chart
description: A generic deployment Helm chart for Kubernetes
type: application
version: 0.0.2
appVersion: "0.0.2"
dependencies:
  - name: "helm-library"
    version: ^2.0.0
    repository: https://bvaughan-nexient.github.io/helm-library